package com.myteam.contract_net;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Bid implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String bidderId;
	private java.lang.String notes;
	private java.lang.Double bidPrice;
	private java.util.Date deliveryDate;

	public Bid() {
	}

	public java.lang.String getBidderId() {
		return this.bidderId;
	}

	public void setBidderId(java.lang.String bidderId) {
		this.bidderId = bidderId;
	}

	public java.lang.String getNotes() {
		return this.notes;
	}

	public void setNotes(java.lang.String notes) {
		this.notes = notes;
	}

	public java.lang.Double getBidPrice() {
		return this.bidPrice;
	}

	public void setBidPrice(java.lang.Double bidPrice) {
		this.bidPrice = bidPrice;
	}

	public java.util.Date getDeliveryDate() {
		return this.deliveryDate;
	}

	public void setDeliveryDate(java.util.Date deliveryDate) {
		this.deliveryDate = deliveryDate;
	}

	public Bid(java.lang.String bidderId, java.lang.String notes,
			java.lang.Double bidPrice, java.util.Date deliveryDate) {
		this.bidderId = bidderId;
		this.notes = notes;
		this.bidPrice = bidPrice;
		this.deliveryDate = deliveryDate;
	}

     @Override
    public String toString() {
        return "Bid{" +
                "bidderId='" + bidderId + '\'' +
                ", notes='" + notes + '\'' +
                ", bidPrice='" + bidPrice + '\'' +
                ", deliveryDate='" + deliveryDate + '\'' +
                '}';
    }
}