package com.myteam.contract_net;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class WorkResult implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String bidderId;
	private java.lang.String result;

	private java.lang.Boolean done;

	public WorkResult() {
	}

	public java.lang.String getBidderId() {
		return this.bidderId;
	}

	public void setBidderId(java.lang.String bidderId) {
		this.bidderId = bidderId;
	}

	public java.lang.String getResult() {
		return this.result;
	}

	public void setResult(java.lang.String result) {
		this.result = result;
	}

	public java.lang.Boolean getDone() {
		return this.done;
	}

	public void setDone(java.lang.Boolean done) {
		this.done = done;
	}

	public WorkResult(java.lang.String bidderId, java.lang.String result,
			java.lang.Boolean done) {
		this.bidderId = bidderId;
		this.result = result;
		this.done = done;
	}
	
	@Override
    public String toString() {
        return "WorkResult{" +
                "bidderId='" + bidderId + '\'' +
                ", result='" + result + '\'' +
                ", done='" + done + '\'' +
                '}';
    }

}